import numpy as np
a=np.arange(10)
print(a)
b=np.append(a,12)
print(b)
print("reverse=",np.flip(b))
c=np.asfarray(b)
print(c)
maximum=np.max(b)
minimum=np.min(b)
print("maximum=",maximum)
print("minimum=",minimum)
